apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dubbo-quick-consumer
  name: dubbo-quick-consumer
  namespace: dubbo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dubbo-quick-consumer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dubbo-quick-consumer
    spec:
      containers:
        - image: polarismesh/dubbo-quick-consumer:0.1.0-3.2.7-SNAPSHOT
          imagePullPolicy: Always
          name: polaris-prometheus
          command:
            - "/bin/bash"
            - "-c"
            - "cd /app && java -jar dubbo-quick-consumer.jar"
          env:
            - name: POLARIS_DISCOVERY_ADDR
              value: "127.0.0.1:8091?namespace=dubbo&token="
            - name: APPLICATION_NAME
              value: "dubbo-consumer"
            - name: REGISTER_MODE
              value: "instance"
            - name: CONFIG_CENTER_ADDR
              value: "127.0.0.1:8093?namespace=dubbo"
            - name: METADATA_REPORT_ADDR
              value: "127.0.0.1:8091?namespace=dubbo&token="
          args:
            - '--config.file=/etc/prometheus/prometheus.yaml'
            - '--web.enable-lifecycle'
          resources:
            limits:
              cpu: "500m"
              memory: 1000Mi
      restartPolicy: Always
