name: Snapshot

on:
  push:
    branches:
      - dubbo-3.2.x
      - dubbo-2.x
      - release/*
    paths-ignore:
      - '**.md'

jobs:
  check-snapshot:
    runs-on: ubuntu-latest
    outputs:
      IS_SNAPSHOT: ${{ steps.set_output_1.outputs.IS_SNAPSHOT }}
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4
      - name: Check deploy type
        id: set_output_1
        run: |
          line="$(grep SNAPSHOT pom.xml || true)"
          echo $line
          if [ -n "$line" ]; then
            echo "IS_SNAPSHOT=true" >> $GITHUB_OUTPUT
          else
            echo "IS_SNAPSHOT=false" >> $GITHUB_OUTPUT
          fi
  set-jdk:
    runs-on: ubuntu-latest
    outputs:
      jdk: ${{ steps.set-jdk.outputs.jdk }}
    steps:
      - name: Set JDK based on branch
        id: set-jdk
        run: |
          shopt -s nocasematch
          if [[ "${{ github.ref_name }}" == "dubbo-3.2.x" ]]; then
            echo "jdk=17" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_name }}" == "dubbo-2.x" ]]; then
            echo "jdk=8" >> $GITHUB_OUTPUT
          else
            echo "jdk=8" >> $GITHUB_OUTPUT
          fi
          shopt -u nocasematch
  snapshot:
    runs-on: ubuntu-latest
    needs: [ check-snapshot, set-jdk ]
    if: ${{ needs.check-snapshot.outputs.IS_SNAPSHOT == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ needs.set-jdk.outputs.jdk }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ needs.set-jdk.outputs.jdk }}
          distribution: 'adopt'
          server-id: central-portal
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: mvn clean deploy -B -U -Dmaven.test.skip=true
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_PORTAL_TOKEN }}
